.TH AUTONETPLAN 1 "13 Marzo 2024"
.SH NOMBRE
autonetplan \- Un programa para gestionar la configuración de redes

.SH SINOPSIS
.B autonetplan
[\fIOPCIONES\fR]
[\fIARGUMENTOS\fR]

.SH DESCRIPCIÓN
autonetplan es un programa que permite gestionar la configuración de redes de forma automatizada.

.SH OPCIONES
.TP
.B \-h, \-\-help
Muestra la ayuda del programa.
